### ISSUE TITLE
FileNotFoundError: user_item_train.relation

### ISSUE THREAD

**Issue by SwaggyZhang** [Abigale001/FairDGE#1]
Hi, thank you for your releasing. 

When I tried to reproduce the experiments, the key file `data/MovieLens/user_item_train.relation` cannot be found from the repo. 

Could you please upload the file or tell my how to obtain that?

Thanks.

**Comment by Abigale001** [comment]
Hi, sorry for the inconvenience. I have just uploaded it to the folder. Thanks for raising this issue.

**Comment by SwaggyZhang** [comment]
> Hi, sorry for the inconvenience. I have just uploaded it to the folder. Thanks for raising this issue.

Thank you!

And could you please upload the code about data preprocessing? Because It is helpful for the readers conducting experiments on other datasets.

Best wishes!

**Comment by SwaggyZhang** [comment]
> Hi, sorry for the inconvenience. I have just uploaded it to the folder. Thanks for raising this issue.

Thank you!

And could you please upload the code about data preprocessing? Because It is helpful for the readers conducting experiments on other datasets.

Best wishes!
